name: Deploy to S3 and Lambda

on:
  push:
    branches:
      - master

# Secrets list
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_SESSION_TOKEN
# - AWS_REGION
# - S3_BUCKET_NAME
# - LAMBDA_FUNCTION_NAME
# - AWS_ROLE_TO_ASSUME (not currently active)
# - AWS_ROLE_EXTERNAL_ID (not currently active)


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x' # Default x64
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          mask-aws-account-id: true
          # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME}}
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          # role-duration-seconds: 1200
          # role-session-name: GitHubAction
      - name: Install zip command
        run: sudo apt install zip
      # - name: Archive directory to zip file
      #   run: zip -r src.zip .
      # - uses: montudor/action-zip@v0.1.0 # 3rd party action using Alpine on docker to zip directory
      #   with:
      #     args: zip -qq src.zip .
      - name: Push to S3
        run: aws s3 sync src.zip s3://${{ secrets.S3_BUCKET_NAME }} --exclude ".git/*" --exclude ".github/*" --delete
      #- name: Update Lambda function code
      #  run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --s3-bucket {{ secrets.S3_BUCKET_NAME }}